import { Movie } from './types';

export const MOVIES: Movie[] = [
  { id: 1, title: 'Final score 2018', embedUrl: 'https://drive.google.com/file/d/1UaOm44pEa3UXcvLtQl-GEFuo35zBA3EN/embed', posterUrl: 'https://picsum.photos/seed/finalscore/400/600' },
  { id: 2, title: 'Regreso a Cold Mountain (2003)', embedUrl: 'https://drive.google.com/file/d/1bBqF-nIRJH1AHwzwBQJZeyNk1Pf4x5u2/embed', posterUrl: 'https://picsum.photos/seed/coldmountain/400/600' },
  { id: 3, title: 'Damisela (2018)', embedUrl: 'https://drive.google.com/file/d/166Kvjqq_GKR9zdo_HdcRXit4eN-wpJXb/embed', posterUrl: 'https://picsum.photos/seed/damisela/400/600' },
  { id: 4, title: 'LA CHICA EN LA TELARAÑA', embedUrl: 'https://drive.google.com/file/d/1bIF4466oOiaogcBnp7q2dlNNGp08SX7r/embed', posterUrl: 'https://picsum.photos/seed/telarana/400/600' },
  { id: 5, title: 'Jurassic Galaxy (2018)', embedUrl: 'https://drive.google.com/file/d/1k2u73Op3rkcqsgOus0NUknzMbOSTNc-t/embed', posterUrl: 'https://picsum.photos/seed/jurassicgalaxy/400/600' },
  { id: 6, title: 'Escape plan 2. Hades 2018', embedUrl: 'https://drive.google.com/file/d/1hU6ZNZstxWnxPOshpM3aAatOb8jrJXat/embed', posterUrl: 'https://picsum.photos/seed/escapeplan2/400/600' },
  { id: 7, title: 'Darc.2018', embedUrl: 'https://drive.google.com/file/d/1ZlLfiQcQJFZkBwOiU56_mNhlDfkFX23I/embed', posterUrl: 'https://picsum.photos/seed/darc/400/600' },
  { id: 8, title: 'El fin de los tiempos (2008)', embedUrl: 'https://drive.google.com/file/d/1FjnkrzkKxCQEUHzSROXDsJsCMq4VVksL/embed', posterUrl: 'https://picsum.photos/seed/findelostiempos/400/600' },
  { id: 9, title: 'Shaft 2019', embedUrl: 'https://drive.google.com/file/d/1-4jxADERMX1cHSvd35snFGPXzUnaSGNj/embed', posterUrl: 'https://picsum.photos/seed/shaft/400/600' },
  { id: 10, title: 'Triple frontera', embedUrl: 'https://drive.google.com/file/d/1CarRupdBYI9FcVJGQ9xI_GIYBXMH_gjF/embed', posterUrl: 'https://picsum.photos/seed/triplefrontera/400/600' },
  { id: 11, title: 'CAZADORA DE GIGANTES', embedUrl: 'https://drive.google.com/file/d/1anuesBY-9boezgghI8Xl0y3abUKw-88O/embed', posterUrl: 'https://picsum.photos/seed/cazadoragigantes/400/600' },
  { id: 12, title: 'Bleach.2018', embedUrl: 'https://drive.google.com/file/d/1xqnFHuWZVmG_x9916edGMQPLFgphrM9P/embed', posterUrl: 'https://picsum.photos/seed/bleach/400/600' },
  { id: 13, title: 'El huracán', embedUrl: 'https://drive.google.com/file/d/15AkqWtubyQhT7Dikr5CvlooqkxwmKpJs/embed', posterUrl: 'https://picsum.photos/seed/elhuracan/400/600' },
  { id: 14, title: 'El Pasajero (2018)', embedUrl: 'https://drive.google.com/file/d/13bwqhWPOKbG9mwaxWqAF_MKBigtI4pby/embed', posterUrl: 'https://picsum.photos/seed/elpasajero/400/600' },
  { id: 15, title: 'Superpoli en Las Vegas', embedUrl: 'https://drive.google.com/file/d/15wpdyDP9BFFny5p2kZwoO609K7Whf93B/embed', posterUrl: 'https://picsum.photos/seed/superpoli/400/600' },
  { id: 16, title: 'Maze runner the death cure 2018', embedUrl: 'https://drive.google.com/file/d/17vwrs0DTBkm4OOjl3CbrnF47qGGNjt57/embed', posterUrl: 'https://picsum.photos/seed/mazerunner/400/600' },
  { id: 17, title: 'Chips 2017', embedUrl: 'https://drive.google.com/file/d/1gYGujac7rDOyNZMKYN9-kPGgzpBnM8Og/embed', posterUrl: 'https://picsum.photos/seed/chips/400/600' },
  { id: 18, title: 'Alita Ángel (2019)', embedUrl: 'https://drive.google.com/file/d/11C2FXa4uZMYUn8cmcQkca_u76UtyaJhC/embed', posterUrl: 'https://picsum.photos/seed/alita/400/600' },
  { id: 19, title: 'Ready Player One (2018)', embedUrl: 'https://drive.google.com/file/d/1FuB5NjG_OTgsUYNIYTSYPqzNl3zdfraG/embed', posterUrl: 'https://picsum.photos/seed/readyplayerone/400/600' },
  { id: 20, title: 'Game overman 2018', embedUrl: 'https://drive.google.com/file/d/18rcOgGi7lmWjmJL2vkDAmYpYtxgDbnC8/embed', posterUrl: 'https://picsum.photos/seed/gameoverman/400/600' },
  { id: 21, title: 'Los 33', embedUrl: 'https://drive.google.com/file/d/1pgnm-GGj51PvywVY-VdQjQhiJPJJFhuA/embed', posterUrl: 'https://picsum.photos/seed/los33/400/600' },
  { id: 22, title: 'JUMANJI 2', embedUrl: 'https://drive.google.com/file/d/1GuDO7_Xl2b1dCmyidTca9QvX49Eyjtld/embed', posterUrl: 'https://picsum.photos/seed/jumanji2/400/600' },
  { id: 23, title: 'GUARDIANES DE LA GALAXIA 2', embedUrl: 'https://drive.google.com/file/d/1c9GN-Xcl6gKiXG_JLvnXrnORV4HPL_ma/embed', posterUrl: 'https://picsum.photos/seed/guardianes2/400/600' },
  { id: 24, title: 'Tomb Raider 3-72', embedUrl: 'https://drive.google.com/file/d/1ykfSCSc-FXFCBOPdu20T-fBWgJK5zk3u/embed', posterUrl: 'https://picsum.photos/seed/tombraider/400/600' },
  { id: 25, title: 'MATAR O MORIR', embedUrl: 'https://drive.google.com/file/d/16CY5hoexURQlbeK4r-Aj_8sjJGgvOkS5/embed', posterUrl: 'https://picsum.photos/seed/mataromorir/400/600' },
  { id: 26, title: 'Furia de Titanes (2010)', embedUrl: 'https://drive.google.com/file/d/1m261_h1Wc6e5BfINKbeoq4OKznoQeEux/embed', posterUrl: 'https://picsum.photos/seed/furiatitanes/400/600' },
  { id: 27, title: 'El Único Sobreviviente', embedUrl: 'https://drive.google.com/file/d/1KkWYTd3vhnO74hYvc1J-_qMHbrCmvIWO/embed', posterUrl: 'https://picsum.photos/seed/unicosobreviviente/400/600' },
  { id: 28, title: 'El bombardeo (2018)', embedUrl: 'https://drive.google.com/file/d/1BfX9bDv6kl47eMaYrA2c-qbxGdETHPUx/embed', posterUrl: 'https://picsum.photos/seed/elbombardeo/400/600' },
  { id: 29, title: 'Crawl [Infierno en la tormenta]', embedUrl: 'https://drive.google.com/file/d/1IcKRi6tl0elutfDd_HtNV2jVc0j-f6xb/embed', posterUrl: 'https://picsum.photos/seed/crawl/400/600' },
  { id: 30, title: 'Fabricated City (2017)', embedUrl: 'https://drive.google.com/file/d/1v7WAMP5ibiUJFz3DQt-roZPlL2Vu71jo/embed', posterUrl: 'https://picsum.photos/seed/fabricatedcity/400/600' },
];